USE BalletShow
GO

-- Sol: SET TRANSACTION ISOLATION LEVEL TO READ COMMITTED
-- we don’t see the update (that is also rollback) – T1 finish first

SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
SELECT * FROM Guests
WAITFOR DELAY '00:00:15'
SELECT * FROM Guests
COMMIT TRAN
