USE BalletShow
GO

-- Sol: SET TRANSACTION ISOLATION LEVEL TO REPEATABLE READ
-- see only the final result in both of the select of T2, T1 finish first

SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN
SELECT * FROM Guests
WAITFOR DELAY '00:00:05'
SELECT * FROM Guests
COMMIT TRAN
